# Run when commits are pushed to main
on:
  workflow_dispatch:
  push:
    branches:
      - main

# Set up permissions for deploying with secretless Azure federated credentials
# https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#set-up-azure-login-with-openid-connect-authentication
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install azd
        uses: Azure/setup-azd@v1.0.0
        with:
          version: 1.10.2
      - name: Log in with Azure (Federated Credentials)
        run: |
          azd auth login `
            --client-id "$Env:AZURE_CLIENT_ID" `
            --federated-credential-provider "github" `
            --tenant-id "$Env:AZURE_TENANT_ID"
        shell: pwsh
      - name: Provision Infrastructure
        run: azd provision --no-prompt
        env:
          AZURE_CLOUDFLARE_ACCOUNT_ID: ${{ secrets.AZURE_CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TUNNELS: ${{ secrets.CLOUDFLARE_API_TUNNELS }}
          AZURE_CF_PRIVATE_KEY: ${{ secrets.AZURE_CF_PRIVATE_KEY }}
          AZURE_VM_PASS: ${{ secrets.AZURE_VM_PASS }}
          AZD_INITIAL_ENVIRONMENT_CONFIG: ${{ secrets.AZD_INITIAL_ENVIRONMENT_CONFIG }}
      - name: Deploy Application
        run: azd deploy --no-prompt
